In [28]:
import json
import pennylane as qml
import pennylane.numpy as np

def U():
    """
    Quantum circuit that facilitates the distribution of goods.
    It should not return anything, you simply need to add the gates.
    """
    def calculate_basis_and_control_values(i):
        bits = [int(b) for b in f"{i:0{10}b}"]
        first_bits = bits[:3]
        last_bits = bits[3:10]
        if sum(bits) == 0:
            return [1, 1, 1], bits
        if sum(bits) % 3 == 0:
            return [0, 0, 0], bits
        if sum(last_bits) % 3 == 0:
            return first_bits, bits
        if sum(last_bits) % 3 == 1:
            if sum(first_bits) == 0:
                return [1, 1, 0], bits
            if sum(first_bits) == 3:
                return [1, 0, 0], bits
            if sum(first_bits) == 1:
                state = [0, 0, 0]
                for i, b in enumerate(first_bits):
                    if b == 0:
                        state[i] = 1
                        break
                return state, bits
        if sum(last_bits) % 3 == 2:
            if sum(first_bits) == 0:
                return [1, 0, 0], bits
            if sum(first_bits) == 3:
                return [1, 1, 0], bits
            if sum(first_bits) == 2:
                state = [0, 0, 0]
                for i, b in enumerate(first_bits):
                    if b == 1:
                        state[i] = 1
                        break
                return state, bits



    # Put your code here #
    for i in range(2 ** 10):
        basis_state, control_values = calculate_basis_and_control_values(i)
        qml.ctrl(
            qml.BasisState(basis_state, wires=(10, 11, 12)),
            control=range(10),
            control_values=control_values
        )
    qml.CNOT(wires=[10, 0])
    qml.CNOT(wires=[11, 1])
    qml.CNOT(wires=[12, 2])






In [29]:

# These functions are responsible for testing the solution.


def run(test_case_input: str) -> str:
    return None


def check(have: str, want: str) -> None:
    have, want = have, want
    params = np.random.rand(10, 2)

    dev = qml.device("default.qubit", wires=13, shots=1000)

    def generate_phi(params, wires):
        for i in range(len(wires)):
            qml.RX(params[i][0], wires=wires[i])

        for i in range(len(wires) - 1):
            qml.CNOT(wires=[i, i + 1])

        for i in range(len(wires)):
            qml.RX(params[i][1], wires=wires[i])

    @qml.qnode(dev)
    def circuit():
        generate_phi(params, wires=range(10))
        U()
        return qml.sample(wires=range(10))

    shots = circuit()
    for shot in shots:
        print(shot)
        assert sum(shot) % 3 == 0, "Wrong answer"

    for op in circuit.tape.operations:
        assert not isinstance(op, qml.QubitUnitary), "You can't use QubitUnitary"
        assert not isinstance(op, qml.measurements.mid_measure.MidMeasureMP), "You cannot use measurements"


# These are the public test cases
test_cases = [
    ('No input', 'No output')
]

# This will run the public test cases locally
for i, (input_, expected_output) in enumerate(test_cases):
    print(f"Running test case {i} with input '{input_}'...")

    try:
        output = run(input_)

    except Exception as exc:
        print(f"Runtime Error. {exc}")

    else:
        if message := check(output, expected_output):
            print(f"Wrong Answer. Have: '{output}'. Want: '{expected_output}'.")

        else:
            print("Correct!")

Running test case 0 with input 'No input'...


[1 1 1 0 0 0 0 0 0 0]
[1 1 0 0 0 1 0 1 1 1]
[1 1 0 0 0 1 0 0 0 0]
[0 0 1 1 0 1 0 0 0 0]
[1 0 1 1 1 1 0 0 1 0]
[1 1 0 0 0 0 0 0 0 1]
[0 1 1 1 1 1 1 1 1 1]
[1 1 0 0 0 0 1 0 0 0]
[1 1 0 0 0 0 1 0 0 0]
[1 1 1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 1 0 1 0]
[0 0 0 1 0 1 1 1 1 1]
[1 0 0 0 0 0 0 0 1 1]
[1 1 0 1 0 0 0 0 0 0]
[1 1 1 0 0 0 0 0 0 0]
[0 0 0 0 0 1 1 0 0 1]
[1 1 0 0 0 0 1 0 0 0]
[0 0 0 1 0 1 0 0 1 0]
[1 1 1 0 0 0 0 0 0 0]
[0 1 1 1 1 1 1 1 1 1]
[1 1 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 1 1]
[1 1 1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 1 1]
[1 1 0 0 0 0 1 1 1 1]
[0 0 0 0 0 0 0 1 1 1]
[1 1 0 0 0 0 1 1 1 1]
[1 1 1 0 0 0 0 0 0 0]
[1 0 0 0 0 1 1 1 1 1]
[1 0 0 0 0 0 0 0 1 1]
[1 1 0 0 0 1 0 0 0 0]
[1 0 1 1 1 0 0 1 1 0]
[0 0 0 1 0 0 0 0 1 1]
[1 0 0 0 0 0 1 1 0 0]
[1 0 0 0 0 0 0 0 1 1]
[1 1 0 0 0 0 0 1 0 0]
[1 0 0 0 0 1 1 0 0 0]
[1 1 0 0 0 0 0 0 0 1]
[1 1 1 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 0 1]
[0 0 1 1 1 1 1 1 0 0]
[1 1 0 1 0 0 0 0 0 0]
[1 1 0 1 0 0 1 1 0 1]
[1 0 0 0 0 0 1 0 0 1]
[1 1 0 0 0 1 0 0 0 0]
[0 0 0 0 0